services:
  landing-dj:
    build: .
    container_name: landing-dj
    restart: always
    ports:
      - "8888:80" # Puedes entrar por http://IP:8888 para probar
    environment:
      - VIRTUAL_HOST=dj.katrix.com.ar
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dj.katrix.com.ar
      - LETSENCRYPT_EMAIL=exe20@gmail.com
    networks:
      - npm_network

networks:
  npm_network:
    external: true
    name: npm_network
